# Generated by Django 5.2.16 on 2026-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0002_alter_roleassignment_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("indstilling", "Indstillingen"),
                    ("inspektion", "Inspektionen"),
                    ("kokkengruppe", "Køkkengruppen"),
                    ("ak", "AK"),
                    ("oelkaelder", "Ølkælderen"),
                    ("regnskab", "Regnskab"),
                    ("pr", "PR"),
                    ("administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
