<?php

// Original by Theis F. Hinz
// Last updated by Nicholas Swiatecki <nicholas@swiatecki.com>
//
// 2026-08-04 — rewritten for the Hetzner migration. Two reasons:
//
// 1. Security. The original interpolated the submitted username straight into SQL:
//
//        $query = "SELECT * FROM `intern_alumne` WHERE (ID='$usernameLow' OR ...) AND ...";
//
//    an unauthenticated SQL injection reachable from the login form by anyone on the internet. It
//    also carried the shared `gahk_dk` password in plaintext, connected to a hardcoded 'localhost',
//    and die()d with the raw mysqli error on failure.
//
// 2. `intern_alumne` no longer exists. Residents live in PostgreSQL as `residents_resident`. The
//    obvious shortcut — freeze a copy of the old table into the wiki database — would have kept the
//    pre-breach unsalted SHA-256 hashes valid on the wiki indefinitely, so the passwords revoked by
//    the forced reset would still open the wiki while the new ones would not. Reading live Postgres
//    avoids that: a reset takes effect here immediately.
//
// Authentication *semantics* are otherwise unchanged (username-or-email, autocreate on first login,
// md5 placeholder name rewritten by GahkAuthChangeName), so this stays a migration, not a redesign.
//
// NOTE: strict() returns true and this is the only primaryauth provider, so local MediaWiki passwords
// are disabled — if Postgres is unreachable, nobody can log in, sysops included. See CUTOVER.md for
// the break-glass procedure.

namespace Gahk;

use MediaWiki\Auth\AuthenticationRequest;
use MediaWiki\Auth\AuthenticationResponse;
use MediaWiki\Auth\LocalPasswordPrimaryAuthenticationProvider;
use MediaWiki\Auth\PasswordAuthenticationRequest;
use MediaWiki\MediaWikiServices;
use Wikimedia\Rdbms\DBError;

class GahkAuthLogin extends LocalPasswordPrimaryAuthenticationProvider
{
//    protected $loginOnly = true;

    function userExists($username)
    {
        return true; // We cannot answer this question without the token
    }

    public function beginPrimaryAuthentication(array $reqs)
    {
        $req = AuthenticationRequest::getRequestByClass($reqs, PasswordAuthenticationRequest::class);
        if (!$req) {
            return AuthenticationResponse::newAbstain();
        }

        if ($req->username === null || $req->password === null) {
            return AuthenticationResponse::newAbstain();
        }

        $loginUsername = $req->username;
        $usernameLow = strtolower(str_replace(' ', '_', $loginUsername));

        $resident = ResidentDirectory::find($usernameLow);
        if ($resident === null) {
            return $this->failResponse($req);
        }
        if (!DjangoPasswords::check($req->password, $resident['password'])) {
            return $this->failResponse($req);
        }

        try {
            $dbr = MediaWikiServices::getInstance()->getDBLoadBalancer()->getConnection(DB_REPLICA);
            $existing = $dbr->selectRow(
                'user',
                'user_name',
                ['user_name' => ucfirst($loginUsername)],
                __METHOD__
            );
        } catch (DBError $e) {
            wfLogWarning('GahkAuthLogin: wiki user lookup failed: ' . $e->getMessage());
            return AuthenticationResponse::newAbstain();
        }

        // Unchanged legacy behaviour: a first-time user with no wiki account is passed through under
        // an md5 placeholder name, which GahkAuthChangeName then rewrites to their e-mail address.
        return AuthenticationResponse::newPass($existing ? $loginUsername : md5($loginUsername));
    }

    public function beginPrimaryAccountCreation($user, $creator, array $reqs)
    {
        return parent::beginPrimaryAccountCreation($user, $creator, $reqs); // TODO: Change the autogenerated stub
    }

    function autoCreate()
    {
        return true;
    }

    function strict()
    {

        // Disable local users in MediaWiki
        return true;
    }

    function canCreateAccounts()
    {

        return false;
    }

}
