# Generated by Django 5.2.15 on 2026-06-27 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("monthly", "Månedlig vurdering (−2)"),
                            ("labour", "Udført arbejde"),
                            ("adjustment", "Manuel justering"),
                            ("opening", "Startsaldo (migreret)"),
                        ],
                        default="adjustment",
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ak_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ak_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["resident", "created_at"], name="ak_akentry_residen_c3b544_idx")
                ],
            },
        ),
    ]
