# Generated by Django 5.2.16 on 2026-08-11 00:49

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_PERIOD_RE = re.compile(r"(\d{4})-(\d{2})$")


def backfill_monthly_periods(apps, schema_editor) -> None:  # noqa: ANN001
    """Populate year/month for existing MONTHLY entries from their 'Månedlig vurdering YYYY-MM' tag,
    so the new (resident, year, month) key is authoritative. Untagged rows stay null (allowed)."""
    ak_entry = apps.get_model("ak", "AkEntry")
    for entry in ak_entry.objects.filter(kind="monthly", year__isnull=True):
        match = _PERIOD_RE.search(entry.reason or "")
        if match:
            entry.year = int(match.group(1))
            entry.month = int(match.group(2))
            entry.save(update_fields=["year", "month"])


def seed_schedule(apps, schema_editor) -> None:  # noqa: ANN001
    """Create the 12 calendar-month schedule rows (default: on, 2 krydser). AK edits them via the UI."""
    charge = apps.get_model("ak", "AkMonthlyCharge")
    for month in range(1, 13):
        charge.objects.get_or_create(month=month, defaults={"krydser": 2, "active": True})


def noop(apps, schema_editor) -> None:  # noqa: ANN001
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ak", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AkMonthlyCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(unique=True)),
                ("krydser", models.PositiveSmallIntegerField(default=2)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["month"],
            },
        ),
        migrations.AddField(
            model_name="akentry",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="akentry",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="akentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("monthly", "Månedlig afregning"),
                    ("labour", "Udført arbejde"),
                    ("adjustment", "Manuel justering"),
                    ("opening", "Startsaldo (migreret)"),
                ],
                default="adjustment",
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_monthly_periods, noop),
        migrations.AddConstraint(
            model_name="akentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "monthly")),
                fields=("resident", "year", "month"),
                name="uniq_ak_monthly_per_period",
            ),
        ),
        migrations.AddField(
            model_name="akmonthlycharge",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ak_charges_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(seed_schedule, noop),
    ]
