# Generated by Django 5.2.16 on 2026-08-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ak", "0002_akmonthlycharge_akentry_month_akentry_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AkAutoApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
