# Generated by Django 5.2.16 on 2026-08-13 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import den_hurtige.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(help_text="Selve beskeden.")),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Valgfrit billede.",
                        max_length=255,
                        upload_to="quick_posts/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=den_hurtige.models.get_default_expiration,
                        help_text="Hvornår opslaget udløber og slettes permanent.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hurtigt opslag",
                "verbose_name_plural": "Hurtige opslag",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuickComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify_everyone",
                    models.BooleanField(
                        default=False,
                        help_text="Sand: push til alle abonnenter. Falsk: kun til opslagets forfatter.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="den_hurtige.quickpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentarer",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quickpost",
            index=models.Index(fields=["expires_at"], name="den_hurtige_expires_0791f1_idx"),
        ),
    ]
