# Generated by Django 5.2.16 on 2026-08-18 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0002_pushsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("emoji", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="den_hurtige.quickpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reaktion",
                "verbose_name_plural": "Reaktioner",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "author", "emoji"), name="uniq_reaction_per_author"
                    )
                ],
            },
        ),
    ]
