# Generated by Django 5.2.16 on 2026-08-18 21:54

from django.conf import settings
from django.db import migrations, models


def keep_one_reaction_per_person(apps, schema_editor) -> None:  # noqa: ANN001
    """Collapse any existing multi-emoji reactions before the new constraint is added.

    Until now a person could stack several emoji on one message. Adding a UNIQUE(post, author)
    over that data would fail the migration outright, so the newest reaction wins and the rest go.
    Reactions live at most a few hours anyway — this only bites a trial database that happens to
    have some in flight.
    """
    QuickReaction = apps.get_model("den_hurtige", "QuickReaction")
    seen = set()
    doomed = []
    for pk, post_id, author_id in QuickReaction.objects.order_by("-created_at", "-pk").values_list(
        "pk", "post_id", "author_id"
    ):
        if (post_id, author_id) in seen:
            doomed.append(pk)
        else:
            seen.add((post_id, author_id))
    QuickReaction.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0003_quickreaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="quickreaction",
            name="uniq_reaction_per_author",
        ),
        migrations.AddField(
            model_name="quickcomment",
            name="image",
            field=models.FileField(
                blank=True, help_text="Valgfrit billede.", max_length=255, upload_to="quick_comments/%Y/%m/"
            ),
        ),
        migrations.RunPython(keep_one_reaction_per_person, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="quickreaction",
            constraint=models.UniqueConstraint(fields=("post", "author"), name="uniq_reaction_per_author"),
        ),
    ]
