# Generated by Django 5.2.17 on 2026-08-23 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0004_remove_quickreaction_uniq_reaction_per_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kanal-mute",
                "verbose_name_plural": "Kanal-mutes",
            },
        ),
        migrations.AddField(
            model_name="quickpost",
            name="channel",
            field=models.CharField(default="generelt", max_length=32),
        ),
        migrations.AddIndex(
            model_name="quickpost",
            index=models.Index(fields=["channel", "expires_at"], name="den_hurtige_channel_69d5ff_idx"),
        ),
        migrations.AddField(
            model_name="channelmute",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_mutes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="channelmute",
            constraint=models.UniqueConstraint(fields=("resident", "channel"), name="uniq_channel_mute"),
        ),
    ]
