# Generated by Django 5.2.17 on 2026-08-24 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Overskrift")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nyt", "Nyt & info"),
                            ("begivenhed", "Begivenhed"),
                            ("vaerelsesrunde", "Værelsesrunden"),
                            ("foedselsdag", "Fødselsdag"),
                            ("praktisk", "Praktisk"),
                            ("andet", "Andet"),
                        ],
                        default="nyt",
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown. Kun kilden gemmes — HTML dannes når opslaget vises.",
                        verbose_name="Indhold",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pinned_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opslag",
                "verbose_name_plural": "Opslag",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(max_length=1000, verbose_name="Kommentar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="opslagstavle.notice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentarer",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(max_length=255, upload_to="opslag/%Y/%m/", verbose_name="Fil")),
                ("alt", models.CharField(blank=True, max_length=255, verbose_name="Beskrivelse")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="opslagstavle.notice",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notice_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billede",
                "verbose_name_plural": "Billeder",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("emoji", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="opslagstavle.notice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reaktion",
                "verbose_name_plural": "Reaktioner",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["category", "-created_at"], name="notice_cat_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="noticeimage",
            index=models.Index(fields=["notice", "uploaded_at"], name="notice_img_orphan_idx"),
        ),
        migrations.AddConstraint(
            model_name="noticereaction",
            constraint=models.UniqueConstraint(
                fields=("notice", "author"), name="uniq_notice_reaction_per_author"
            ),
        ),
    ]
