# Generated by Django 5.2.17 on 2026-08-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("opslagstavle", "0002_fold_title_into_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="events.event",
                verbose_name="Begivenhed",
            ),
        ),
    ]
