# Generated by Django 5.2.17 on 2026-08-20 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_page_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(max_length=255, upload_to="cms/%Y/%m/", verbose_name="Fil")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Bruges som alt-tekst.",
                        max_length=255,
                        verbose_name="Beskrivelse",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cms_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billede",
                "verbose_name_plural": "Billeder",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
