# Generated by Django 5.2.15 on 2026-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomconditionscore_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomconditionscore',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
