# Generated by Django 5.2 on 2026-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_roomconditionscore_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomconditionscore",
            name="photo",
            field=models.FileField(blank=True, max_length=255, upload_to="roomimages/%Y/"),
        ),
    ]
