# Generated by Django 5.2.16 on 2026-08-10 19:58, then split (dedup here, constraint in 0006) so the
# post-delete ALTER doesn't hit Postgres "pending trigger events" in the same transaction.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_applications(apps, schema_editor) -> None:  # noqa: ANN001
    """Enforce one application per (resident, move_month) before the constraint is added in 0006.

    The old view always INSERTed, so prod (and the legacy-migrated 15) can hold duplicates. Keep the
    most recent apply_datetime per group — the resident's latest intent, matching the new overwrite
    semantics — and delete the rest (cascades priorities + orlov). Idempotent.
    """
    KvotientApplication = apps.get_model("rooms", "KvotientApplication")
    seen: set[tuple[int, int]] = set()
    stale: list[int] = []
    for app in KvotientApplication.objects.order_by("-apply_datetime", "-id"):
        key = (app.resident_id, app.move_month)
        if key in seen:
            stale.append(app.id)
        else:
            seen.add(key)
    KvotientApplication.objects.filter(id__in=stale).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_roomconditionscore_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roomoffer",
            name="awarded_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rooms.kvotientapplication",
            ),
        ),
        migrations.RunPython(dedupe_applications, migrations.RunPython.noop),
    ]
