# Generated by Django 5.2.16 on 2026-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaning",
            name="size",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workgroup",
            name="size",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
