# Generated by Django 5.2.16 on 2026-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_regnskab_workgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevClock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("simulated_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
