# Generated by Django 5.2.17 on 2026-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="wants_begivenheder",
            field=models.BooleanField(default=False, verbose_name="Begivenheder"),
        ),
    ]
