# Generated by Django 5.2.17 on 2026-08-29 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import events.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=events.models._new_feed_token, editable=False, max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender-token",
                "verbose_name_plural": "Kalender-tokens",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beskrivelse")),
                (
                    "image",
                    models.FileField(
                        blank=True, max_length=255, upload_to="begivenheder/%Y/%m/", verbose_name="Billede"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=140, verbose_name="Sted")),
                ("starts_at", models.DateTimeField(verbose_name="Starter")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Slutter")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("aabent", "Åbent for alle beboere"), ("kun_inviterede", "Kun inviterede")],
                        default="aabent",
                        max_length=16,
                        verbose_name="Synlighed",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Antal pladser"),
                ),
                ("rsvp_deadline_at", models.DateTimeField(blank=True, null=True, verbose_name="Svarfrist")),
                ("sequence", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "co_organisers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_co_organised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Medarrangører",
                    ),
                ),
                (
                    "organiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_organised",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arrangør",
                    ),
                ),
            ],
            options={
                "verbose_name": "Begivenhed",
                "verbose_name_plural": "Begivenheder",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EventInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="events.event"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitationer",
            },
        ),
        migrations.CreateModel(
            name="Rsvp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answer", models.CharField(choices=[("ja", "Ja"), ("nej", "Nej")], max_length=4)),
                ("answered_at", models.DateTimeField()),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rsvps", to="events.event"
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tilmelding",
                "verbose_name_plural": "Tilmeldinger",
                "ordering": ["answered_at", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["starts_at"], name="event_starts_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventinvite",
            constraint=models.UniqueConstraint(fields=("event", "resident"), name="uniq_event_invite"),
        ),
        migrations.AddConstraint(
            model_name="rsvp",
            constraint=models.UniqueConstraint(fields=("event", "resident"), name="uniq_rsvp_per_resident"),
        ),
    ]
