# Generated by Django 5.2.15 on 2026-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oelkaelder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, max_length=500, upload_to="oel/"),
        ),
    ]
