# Generated by Django 5.2.16 on 2026-08-03 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oelkaelder", "0002_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("rate_percent", models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ("threshold_ore", models.IntegerField(default=-10000)),
            ],
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_ore", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("interest", "Rente"), ("manual", "Manuel justering")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "shopper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="oelkaelder.shopper",
                    ),
                ),
            ],
        ),
    ]
