# Generated by Django 5.2.16 on 2026-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oelkaelder", "0004_seed_warnings_and_interest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["-created_at", "-id"], name="oelk_txn_created_id_idx"),
        ),
    ]
