# Generated by Django 5.2.16 on 2026-08-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oelkaelder", "0005_transaction_created_at_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("block_below_ore", models.IntegerField(default=-10000)),
            ],
            options={
                "verbose_name": "Købsgrænse",
                "verbose_name_plural": "Købsgrænser",
            },
        ),
    ]
