# Generated by Django 5.2.17 on 2026-08-31 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oelkaelder", "0006_purchasepolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OelkaelderOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price_text", models.CharField(blank=True, max_length=80)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ølkældertilbud",
                "verbose_name_plural": "Ølkældertilbud",
                "ordering": ["priority", "starts_at", "-created_at"],
            },
        ),
    ]
