# Generated by Django 5.2.15 on 2026-06-27 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["type", "submitted_at"], name="admissions__type_e967ff_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["received_by"], name="admissions__receive_4d84a2_idx"),
        ),
    ]
